// Generated by Wrangler by running `wrangler types`

interface Env {
  ENVIRONMENT: 'production';
  SESSION_REGISTRY: DurableObjectNamespace<import('./src/index').SessionRegistry>;
  WORK_QUEUE: DurableObjectNamespace<import('./src/index').WorkQueue>;
  CARD_LOCK: DurableObjectNamespace<import('./src/index').CardLock>;
}
